In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
os.listdir('Dataset')

['baseline_0.csv',
 'ratings.csv',
 'remarks.csv',
 'remarks_supp_opp.csv',
 'test.csv',
 'train.csv']

In [3]:
for file in os.listdir('Dataset'):
#     print(file)
    data = pd.read_csv('Dataset/' + file)
    print(file, data.shape)
    print(data.head(), '\n')

baseline_0.csv (882, 2)
     id  left
0   353     0
1   732     0
2  3076     0
3  2199     0
4  2145     0

ratings.csv (221232, 4)
   emp      comp        Date  rating
0   31  bnivzbfi  01-02-2016       4
1   33  bnivzbfi  01-02-2016       4
2   79  bnivzbfi  01-02-2016       4
3   94  bnivzbfi  01-02-2016       4
4   16  bnivzbfi  01-02-2016       2

remarks.csv (82756, 5)
   emp      comp  remarkId                                                txt  \
0  307  bnivzbfi  fvwadfrj  **********************************************...
1  382  bnivzbfi  xrrfkgap                      *****************************
2  172  bnivzbfi  xkcrccwi                        ***************************
3  135  bnivzbfi  lohhvtmo                        ***************************
4  225  bnivzbfi  gpxxmoab                  *********************************

   remarkDate
0  20-03-2017
1  20-03-2017
2  20-03-2017
3  20-03-2017
4  20-03-2017

remarks_supp_opp.csv (336960, 5)
   emp      comp support oppose  remarkId
0  307  bnivzbfi    True  False  fvwadfrj
1   36  bnivzbfi    True  False  fvwadfrj
2  276  bnivzbfi    True  False  fvwadfrj
3   24  bnivzbfi    True  False  fvwadfrj
4  382  bnivzbfi    True  False  xrrfkgap

test.csv (882, 4)
     id  emp      comp lastratingdate
0   353  509  bnivzbfi     20-03-2017
1   732   22  ocsicwng     17-03-2017
2  3076    2  siexkzzo     09-01-2017
3  2199  885  phcvroct     01-10-2016
4  2145  756  phcvroct     06-02-2017

train.csv (3526, 5)
     id  emp      comp lastratingdate  left
0  2228  939  phcvroct     17-10-2016     1
1  4349  250  jblrepyr     19-03-2017     0
2   945  134  ewpvmfbc     21-09-2016     0
3  4553  164  wsmblohy     17-03-2017     0
4   941  129  ewpvmfbc     04-04-2016     0

C:\Users\nithy\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (2,3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [10]:
os.listdir('Dataset')

['baseline_0.csv',
 'ratings.csv',
 'remarks.csv',
 'remarks_supp_opp.csv',
 'test.csv',
 'train.csv']

In [19]:
ratings = pd.read_csv('Dataset/ratings.csv')
remarks = pd.read_csv('Dataset/remarks.csv')

In [23]:
remarks.rename({'remarkDate':'Date'}, axis=1, inplace=True)

In [31]:
remarks_ratings = ratings.merge(remarks, how='outer')

In [56]:
remarks_ratings.replace(np.nan, '', inplace = True)

In [57]:
remarks_ratings['rating'].replace('', np.nan, inplace = True)

In [58]:
remarks_ratings

,emp,comp,Date,rating,remarkId,txt
0,31,bnivzbfi,01-02-2016,4.0,eytkoctg,************************************************
1,31,bnivzbfi,01-02-2016,4.0,eytkoctg,************************************************
2,33,bnivzbfi,01-02-2016,4.0,syeuglak,**********************************************...
3,33,bnivzbfi,01-02-2016,4.0,syeuglak,**********************************************...
4,79,bnivzbfi,01-02-2016,4.0,xsmxtprf,**********************************
...,...,...,...,...,...,...
266659,-47,wsmblohy,22-02-2017,NaN,gngdsitv,**********************************************...
266660,-17,wsmblohy,22-02-2017,NaN,nvxgappk,****************
266661,-14,wsmblohy,22-02-2017,NaN,ajhaxikw,**********************************************...
266662,-51,wsmblohy,22-02-2017,NaN,whwflgqb,**********************************************...
266663,361,wsmblohy,,NaN,iwzwsvic,

In [60]:
from datetime import datetime

datetime_object = datetime.strptime('Jun 1 2005  1:33PM', '%b %d %Y %I:%M%p')

In [77]:
remarks_ratings['Date'] = remarks_ratings['Date'].apply(lambda d: datetime.strptime(d, '%d-%m-%Y').date() if d != ''else '')

In [36]:
comps = np.unique(remarks_ratings['comp'].values)

In [90]:
dates = sorted(np.unique(remarks_ratings['Date'].values[np.argwhere(remarks_ratings['Date'].values != '')]).tolist())

In [102]:
day_gaps = []
for i in range(len(dates)-1):
    day_gaps.append((dates[i+1]-dates[i]).days)
day_gaps

[171,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 4,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 7,
 7,
 1,
 1,
 13,
 5,
 13,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]